name: Github Action Warmup
run-name: ${{ github.actor }} is building the project
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps: 
        - run: node --version
        - run: npm --version
        - uses: actions/checkout@v3
        - run: npm ci
        - run: node app.js